version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'type: dependencies'
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: "saturday"
